- name: ensure user is present
  hosts:  all
  tasks:
    - win_user:
        name: "{{ logon }}"
        password: "{{ password }}"
        state: present
        groups-action: add
        groups:
          - Domain Users
          - cloud-users
          - rdp-users
          - login-users
          
