- name: update user password
  hosts:  all
  tasks:
    - win_user:
        name: "{{ logon }}"
        state: query
      register: user_info
      failed_when: user_info.state != "present"
    - win_user:
        name: "{{ logon }}"
        password: "{{ password }}"
#    - debug: var=user_info
